name: Weather-App-Build
on:
  push:
    branches:
      - main
    paths:
      - 'application/**'
      - '.github/workflows/app.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push image to ECR
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log in to ECR
        working-directory: ./application
        run: make login
        env:
          ACR_URL: ${{ secrets.ACR_URL }}
          ACR_USER: ${{ secrets.ACR_USER }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

      - name: Build weather-app image
        working-directory: ./application
        env:
          ACR_URL: ${{ secrets.ACR_URL }}
          ACR_USER: ${{ secrets.ACR_USER }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: make build

      - name: Push weather-app image to ECR
        working-directory: ./application
        env:
          ACR_URL: ${{ secrets.ACR_URL }}
          ACR_USER: ${{ secrets.ACR_USER }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: make push



