name: Destroy-Infrastructure
on:
  push:
    branches:
      - destroy
    paths:
      - 'infrastructure/**'
      - '.github/workflows/destroy.yml'

jobs:
  terraform_destroy_plan:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Plan
      working-directory: ./infrastructure
      run: make run_destroy_plan       

  terraform_destroy_apply:
    environment:
      name: approval
    needs: terraform_destroy_plan
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Apply
      working-directory: ./infrastructure
      run: make run_destroy_apply 


